import Verso
import VersoManual
import VersoBlueprint
import Flypitch.RegularOpenAlgebra

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option linter.hashCommand false

#doc (Manual) "Complete Boolean Algebras" =>

The central algebraic structure for the forcing proof is the *complete Boolean
algebra*. In classical logic, truth values are drawn from the two-element
Boolean algebra $`\{\text{true}, \text{false}\}`$. Forcing generalizes
this: truth values are drawn from an arbitrary complete Boolean algebra
$`\mathbb{B}`$. This chapter develops the necessary theory.

# Boolean Algebras

:::definition "def:boolean-algebra"
A *Boolean algebra* is a set $`\mathbb{B}`$ equipped with:
- a partial order $`\leq`$,
- binary operations $`\sqcap`$ (meet) and $`\sqcup`$ (join),
- a unary operation $`\cdot^c`$ (complement),
- distinguished elements $`\top`$ (top) and $`\bot`$ (bottom),

satisfying the usual axioms: $`(\mathbb{B}, \sqcap, \sqcup)`$ is a distributive
lattice with top $`\top`$ and bottom $`\bot`$, and for each element
$`a \in \mathbb{B}`$, we have $`a \sqcap a^c = \bot`$ and
$`a \sqcup a^c = \top`$.
:::

In Lean, this structure is provided by the typeclass `CompleteBooleanAlgebra`,
which is part of mathlib. It extends the lattice structure with the completeness
axiom: every subset has a supremum (join) and an infimum (meet).

# Complete Boolean Algebras

:::definition "def:complete-boolean-algebra"
A *complete Boolean algebra* is a Boolean algebra $`\mathbb{B}`$ in which
every subset $`S \subseteq \mathbb{B}`$ has a least upper bound
$`\bigsqcup S`$ (supremum) and a greatest lower bound
$`\bigsqcap S`$ (infimum). In particular, the empty join is $`\bot`$
and the empty meet is $`\top`$.
:::

The key algebraic fact is that in a complete Boolean algebra, the infinitary
distributive laws hold: for any family $`\{a_i\}_{i \in I}`$ and any
$`b`$,
$`b \sqcap \left(\bigsqcup_i a_i\right) = \bigsqcup_i (b \sqcap a_i)`$
and dually. This allows the manipulation of quantifiers as infinitary joins and
meets.

Following standard set-theoretic convention, we also use the *implication*
operation (relative pseudocomplement): $`a \Rightarrow b`$ is defined as
$`a^c \sqcup b`$. This satisfies $`c \sqcap a \leq b`$ if and only if
$`c \leq a \Rightarrow b`$, making it the right adjoint to meet.

:::lemma_ "lem:le-imp-iff" (lean := "Flypitch.bSet.le_imp_iff")
In a complete Boolean algebra, $`c \sqcap a \leq b`$ if and only if
$`c \leq a \Rightarrow b`$.
:::

# Regular Open Sets

The primary source of complete Boolean algebras in forcing is the algebra of
*regular open sets* of a topological space.

:::definition "def:regular-open" (lean := "Flypitch.RegularOpenAlgebra.is_regular")
Let $`X`$ be a topological space. A set $`S \subseteq X`$ is *regular open* if
$`S = \operatorname{int}(\operatorname{cl}(S))`$: it is the interior of its
own closure.
:::

Equivalently, $`S`$ is regular open when it equals its double
pseudocomplement. The *pseudocomplement* (or *perp*) of $`S`$ is defined as
the interior of the complement of $`S`$:

$`S^\perp = \operatorname{int}(X \setminus S)`$

:::definition "def:perp" (lean := "Flypitch.RegularOpenAlgebra.perp")
The *pseudocomplement* of a set $`S \subseteq X`$ is
$`S^\perp = \operatorname{int}(X \setminus S)`$, the largest open set
disjoint from $`S`$.
:::

A set is regular open precisely when $`S = S^{\perp\perp}`$. The collection of
all regular open subsets of $`X`$, denoted $`\text{RO}(X)`$, forms a complete
Boolean algebra:

- The partial order is inclusion: $`S \leq T`$ iff $`S \subseteq T`$.
- The meet $`S \sqcap T`$ is ordinary intersection $`S \cap T`$ (which is
  regular open when $`S`$ and $`T`$ are).
- The join $`S \sqcup T`$ is $`(S \cup T)^{\perp\perp}`$, the
  regularization of the ordinary union.
- The complement $`S^c`$ is $`S^\perp`$.
- The supremum of a family $`\{S_i\}`$ is
  $`\left(\bigcup_i S_i\right)^{\perp\perp}`$.
- The infimum is $`\left(\bigcap_i S_i\right)^{\perp\perp}`$
  (or, equivalently, the interior of the closure of the intersection).

:::theorem "thm:regular-open-algebra"
$`\text{RO}(X)`$ is a complete Boolean algebra for any topological space
$`X`$.
:::

This is the fundamental construction underlying both the Cohen and the collapse
Boolean algebras. In Chapter {uses "sec:cohen-forcing"}[], we will take $`X`$
to be the Cantor space $`2^{\aleph_2 \times \mathbb{N}}`$ with the product
topology. In Chapter {uses "sec:collapse-forcing"}[], we will take $`X`$ to be
the space of partial functions $`\aleph_1 \rightharpoonup
\mathcal{P}(\mathbb{N})`$ with the topology generated by a suitable basis.

:::proof "proof:regular-open-algebra"
The verification that $`\text{RO}(X)`$ is a complete Boolean algebra proceeds
as follows:

1. **Regular open sets form a Boolean algebra under $`\cap, \perp`$.** For any
   regular open $`S`$ and $`T`$, the intersection $`S \cap T`$ is open and
   satisfies $`(S \cap T)^{\perp\perp} = S \cap T`$, so it is regular. The
   pseudocomplement $`S^\perp`$ is open by definition and satisfies
   $`S^{\perp\perp\perp} = S^\perp`$, making it regular.

2. **Completeness.** For an arbitrary family $`\{S_i\}_{i \in I}`$ of regular
   open sets, define the join as $`\left(\bigcup_i S_i\right)^{\perp\perp}`$.
   This is regular open (it is a double pseudocomplement) and is the least
   regular open set containing all $`S_i`$. The meet is dually
   $`\left(\bigcap_i S_i\right)^{\perp\perp}`$, or simply
   $`\bigcap S_i`$ when the family is finite.

3. **Infinite distributivity** follows from the definition of joins via
   pseudocomplement and the fact that $`\cap`$ distributes over
   $`\bigcup`$ in the underlying set algebra.
:::

The pseudocomplement operation has several useful properties. For open sets
$`S`$ and $`T`$:
- $`S \subseteq S^{\perp\perp}`$ (inflationary on opens)
- $`S^{\perp\perp\perp} = S^\perp`$
- $`S^\perp = S^{\perp\perp\perp}`$
- If $`S`$ is clopen, then $`S`$ is regular open.

These properties are used extensively in the forcing proofs to manipulate truth
values of formulas in the Boolean-valued universe.

# Examples

We will encounter two specific complete Boolean algebras:

1. **The Cohen algebra** $`\mathbb{B}_{\text{Cohen}} =
   \text{RO}(2^{\aleph_2 \times \mathbb{N}})`$, the regular opens
   of the Cantor space with the product topology. This algebra has the countable
   chain condition (CCC), a property that plays a role in cardinal preservation.

2. **The collapse algebra** $`\mathbb{B}_{\text{Collapse}} =
   \text{RO}(\mathcal{P}_{\omega_1}(\aleph_1 \times
   \mathcal{P}(\mathbb{N})))`$, the regular opens of the collapse poset
   topology. This algebra is designed to add a surjection from
   $`\aleph_1`$ onto $`\mathcal{P}(\mathbb{N})`$.

Both algebras are defined and studied in detail in their respective chapters.
