import Verso
import VersoManual
import VersoBlueprint
import Flypitch.ForcingCH
import Flypitch.Collapse
import Flypitch.AlephOne

open Verso.Genre
open Verso.Genre.Manual
open Informal

set_option linter.hashCommand false

#doc (Manual) "Collapse Forcing — CH Holds" =>

The second Boolean-valued model we construct is the collapse extension, in which
the Continuum Hypothesis is forced to be true. The idea is to "collapse" the
cardinal $`\aleph_1`$ onto the continuum: we adjoin a generic surjection
from $`\aleph_1`$ onto $`\mathcal{P}(\omega)`$, so that
$`|\mathcal{P}(\omega)| \leq \aleph_1`$. Since
$`\aleph_1 \leq |\mathcal{P}(\omega)|`$ holds in ZFC, this forces
$`|\mathcal{P}(\omega)| = \aleph_1`$, which is exactly CH.

# The Collapse Poset

:::definition "def:collapse-poset" (lean := "Flypitch.Collapse.collapse_poset")
The *collapse poset* $`\mathbb{P}_{\text{Collapse}}`$ consists of all partial
functions $`p : \aleph_1 \rightharpoonup \mathcal{P}(\omega)`$ whose
domain is at most countable. Functions are ordered by reverse inclusion:
$`p \leq q`$ iff $`p`$ extends $`q`$ (as a function).
:::

The partial functions in this poset represent "finite (or countable) amounts of
information" about a putative function from $`\aleph_1`$ *onto*
$`\mathcal{P}(\omega)`$. The generic filter will assemble these fragments
into a total surjection.

The collapse poset is an important example in forcing theory. Unlike the Cohen
poset (which adds subsets of $`\omega`$), the collapse poset collapses the
cardinal $`\aleph_1`$ onto $`\mathcal{P}(\omega)`$ in the extension,
making the continuum have size exactly $`\aleph_1`$.

# The Collapse Boolean Algebra

As with the Cohen algebra, we form the complete Boolean algebra of regular open
sets of the collapse poset's associated topological space.

:::definition "def:collapse-BA" (lean := "Flypitch.ForcingCH.collapse_algebra.𝔹_collapse")
The *collapse Boolean algebra* $`\mathbb{B}_{\text{Collapse}}`$ is the
complete Boolean algebra of regular open subsets of the collapse poset
$`\mathbb{P}_{\text{Collapse}}`$, where the topology is generated by basic
open sets $`U_p = \{q \in \mathbb{P}_{\text{Collapse}} \mid q \leq p\}`$ for
each $`p \in \mathbb{P}_{\text{Collapse}}`$.
:::

# The Generic Surjection

The heart of the collapse construction is building a Boolean-valued function
$`\pi : \aleph_1 \to \mathcal{P}(\omega)`$ that is *surjective* in the
Boolean-valued sense.

:::definition "def:collapse-pi" (lean := "Flypitch.ForcingCH.collapse_algebra.π")
The Boolean-valued relation $`\pi`$ is defined as a Boolean-valued set of
ordered pairs $`\langle\eta, S\rangle`$ for $`\eta < \aleph_1`$ and
$`S \subseteq \omega`$ (formally, $`S \in \mathcal{P}(\omega)`$). The
truth value that $`\pi(\eta) = S`$ is given by the principal open
$`U_{(\eta, S)}`$ where $`(\eta, S)`$ is the singleton partial function
mapping $`\eta`$ to $`S`$.
:::

:::lemma_ "lem:pi-is-total" (lean := "Flypitch.ForcingCH.collapse_algebra.π_is_total")
$`\pi`$ is a total relation: for every $`\eta < \aleph_1`$, there is some
$`S \subseteq \omega`$ such that $`\pi(\eta) = S`$ has positive truth value.
:::

:::lemma_ "lem:pi-is-surj" (lean := "Flypitch.ForcingCH.collapse_algebra.π_is_surj_onto")
$`\pi`$ is surjective in the Boolean-valued sense: for every $`S \subseteq
\omega`$, the truth value that $`\exists \eta < \aleph_1,\ \pi(\eta) = S`$ is
$`\top`$.
:::

:::lemma_ "lem:pi-is-func" (lean := "Flypitch.ForcingCH.collapse_algebra.π_is_func'")
$`\pi`$ is a function in the Boolean-valued sense: for any $`\eta`$,
$`\pi(\eta)`$ is uniquely determined (Boolean-valued equality of the output
for the same input has truth value $`\top`$).
:::

Together, these lemmas establish that $`\pi`$ is a genuine Boolean-valued
surjective function from $`\aleph_1`$ onto $`\mathcal{P}(\omega)`$.

# $`\aleph_1`$ Surjects onto the Continuum

:::theorem "thm:aleph1-surjects-continuum" (lean := "Flypitch.ForcingCH.aleph_one_larger_than_powerset_omega")
In the collapse Boolean-valued model $`V^{\mathbb{B}_{\text{Collapse}}}`$,
there is a surjection from $`\aleph_1`$ onto $`\mathcal{P}(\omega)`$.
Equivalently, $`|\mathcal{P}(\omega)| \leq \aleph_1`$ is forced.
:::

:::proof "proof:aleph1-surjects-continuum"
The function $`\pi`$ constructed above is a Boolean-valued function with
domain $`\aleph_1`$ and codomain $`\mathcal{P}(\omega)`$. Its totality
({uses "lem:pi-is-total"}[]) and surjectivity
({uses "lem:pi-is-surj"}[]) mean that for every $`S \in
\mathcal{P}(\omega)`$, the truth value $`\exists \eta \in \aleph_1,\
\pi(\eta) = S`$ is $`\top`$. Its functionality ({uses "lem:pi-is-func"}[])
means it is genuinely a function. Thus $`\pi`$ witnesses that
$`\aleph_1`$ surjects onto $`\mathcal{P}(\omega)`$, which means
$`|\mathcal{P}(\omega)| \leq \aleph_1`$.
:::

# CH Is Forced True

:::theorem "thm:ch-forced" (lean := "Flypitch.ForcingCH.collapse_algebra.CH₂_true")
In the collapse Boolean-valued model $`V^{\mathbb{B}_{\text{Collapse}}}`$,
the continuum hypothesis $`\mathrm{CH}_2`$ receives truth value $`\top`$.
Equivalently, $`\top \Vdash_{V^{\mathbb{B}_{\text{Collapse}}}}
\mathrm{CH}_2`$.
:::

:::proof "proof:ch-forced"
$`\mathrm{CH}_2`$ states that every ordinal of cardinality at most continuum is
countable. Equivalently, there is no cardinal strictly between
$`\omega`$ and $`\mathcal{P}(\omega)`$. Since we have constructed a
surjection from $`\aleph_1`$ onto $`\mathcal{P}(\omega)`$, it follows
that $`|\mathcal{P}(\omega)| \leq \aleph_1`$. Together with the ZFC
theorem that $`\aleph_1 \leq |\mathcal{P}(\omega)|`$, we obtain
$`|\mathcal{P}(\omega)| = \aleph_1`$. Therefore there is no room for an
intermediate cardinal, and $`\mathrm{CH}_2`$ has truth value $`\top`$.
:::

:::corollary "cor:CH-true" (lean := "Flypitch.ForcingCH.collapse_algebra.CH_true")
Since $`\mathrm{CH}_f`$ and $`\mathrm{CH}_2`$ are equivalent
({uses "lem:CH-iff-CH2"}[]), $`\mathrm{CH}_f`$ also receives truth value
$`\top`$ in $`V^{\mathbb{B}_{\text{Collapse}}}`$.
:::

# Corollary: ZFC Does Not Prove Not-CH

By Boolean-valued soundness, if ZFC proved $`\neg\mathrm{CH}_f`$, then
$`\neg\mathrm{CH}_f`$ would be forced true in every Boolean-valued model of
ZFC, including the collapse model. But in the collapse model, CH is forced true,
so $`\neg\mathrm{CH}_f`$ has truth value $`\bot`$. This is a contradiction.
Therefore ZFC does not prove $`\neg\mathrm{CH}_f`$:

$`\text{ZFC} \not\vdash' \neg\mathrm{CH}_f`$

The formal Lean statement of this corollary is
{uses "thm:not-ch-unprovable"}[] in Chapter {uses "sec:independence"}[].
